### ISSUE TITLE
Migrate submissions to Firebase

### ISSUE THREAD

**Issue by danmt** [solanau/the-challenger#2]
# Description

Using GitHub to store the submissions sucks. Instead, we should be using Firebase.

## Tasks

- [x] Create submissions only in Firebase.
- [x] List submissions from Firebase. (filter by status)
- [x] Allow users to change a submission status.
