### ISSUE TITLE
Replace Github Authentication with Firebase Authentication

### ISSUE THREAD

**Issue by danmt** [solanau/the-challenger#3]
# Description

We were using GitHub as a data storage, once #2 is closed, it doesn't make sense to keep using GitHub authentication. Instead, we should be replacing it with Firebase authentication and providing a wider range of identity providers. Using Firebase Authentication opens the door for using the client SDK which might help us reduce some code and get the most out of Firebase.

## Tasks

- [x] Replace GitHub auth with Firebase auth.
- [x] Let users create a federated profile.
- [x] Let users link a wallet with their profile.
- [x] Authenticate user for submissions and review.
